"""denormalize_appointments

Revision ID: 4afa469aa4b8
Revises: e7605e1e8ff6
Create Date: 2026-07-05 04:50:56.468050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afa469aa4b8'
down_revision: Union[str, Sequence[str], None] = 'e7605e1e8ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('appointments', 'patient_name')
    # ### end Alembic commands ###
